/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cwsmanager.model.telas;


    // Variables declaration - do not modify                     
/**
 *
 * @author EduardoGreco
 */
public class CadastroCliente extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public CadastroCliente() {
    //    initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPaneDadosCliente = new javax.swing.JTabbedPane();
        jTabbedPaneDadosCliente1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabelCodigo1 = new javax.swing.JLabel();
        jLabelCpfCnpj1 = new javax.swing.JLabel();
        jTextFieldNome1 = new javax.swing.JTextField();
        jLabelData1 = new javax.swing.JLabel();
        jLabelEmail1 = new javax.swing.JLabel();
        jLabelTelPessoal1 = new javax.swing.JLabel();
        jLabelCel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelDataNasc1 = new javax.swing.JLabel();
        jFormattedTextFieldDataNasc1 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCpfCnpj1 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelComecial1 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefonePessoal1 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCelularHum1 = new javax.swing.JFormattedTextField();
        jRadioButtonMasculino1 = new javax.swing.JRadioButton();
        jLabelSexo1 = new javax.swing.JLabel();
        jRadioButtonFeminino1 = new javax.swing.JRadioButton();
        jFormattedTextFieldDataCadastro1 = new javax.swing.JFormattedTextField();
        jLabelNome2 = new javax.swing.JLabel();
        jButtonPesquisar1 = new javax.swing.JButton();
        jTextFieldEmailEmail1 = new javax.swing.JTextField();
        jLabelEmail3 = new javax.swing.JLabel();
        jFormattedTextFieldCpfCnpj2 = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanelEndereco1 = new javax.swing.JPanel();
        jComboBoxCidade1 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldComplemento1 = new javax.swing.JTextField();
        jTextFieldLogradouro1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabelTipoLogradouro1 = new javax.swing.JLabel();
        jTextFieldBairro1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jComboBoxTipoLogradouro1 = new javax.swing.JComboBox();
        jComboBoxUf1 = new javax.swing.JComboBox();
        jFormattedTextFieldCep1 = new javax.swing.JFormattedTextField();
        jPanelEndereco3 = new javax.swing.JPanel();
        jLabelTipoLogradouro2 = new javax.swing.JLabel();
        jComboBoxTipoLogradouro2 = new javax.swing.JComboBox();
        list1 = new java.awt.List();
        jPanelEndereco2 = new javax.swing.JPanel();
        jTextFieldComplemento2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldBairro2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jButtonIncluirPF = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPaneDadosCliente.setBackground(new java.awt.Color(207, 207, 207));

        jTabbedPaneDadosCliente1.setBackground(new java.awt.Color(207, 207, 207));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCodigo1.setText("Código: ");
        jPanel3.add(jLabelCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabelCpfCnpj1.setText("CPF:");
        jPanel3.add(jLabelCpfCnpj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        jTextFieldNome1.setBackground(new java.awt.Color(254, 253, 250));
        jTextFieldNome1.setForeground(new java.awt.Color(22, 20, 9));
        jTextFieldNome1.setMaximumSize(new java.awt.Dimension(42, 28));
        jTextFieldNome1.setMinimumSize(new java.awt.Dimension(42, 28));
        jTextFieldNome1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanel3.add(jTextFieldNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 500, -1));

        jLabelData1.setText("Data de Cadastro: ");
        jPanel3.add(jLabelData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 140, 20));

        jLabelEmail1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEmail1.setText("Telefone Comercial:");
        jPanel3.add(jLabelEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 20));

        jLabelTelPessoal1.setText("Telefone Pessoal:");
        jPanel3.add(jLabelTelPessoal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabelCel4.setText("Celular:");
        jPanel3.add(jLabelCel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, 20));

        jLabel13.setText("Email: ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 630, -1, -1));

        jLabelDataNasc1.setText("Data de nascimento: ");
        jPanel3.add(jLabelDataNasc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 20));

        try {
            jFormattedTextFieldDataNasc1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataNasc1.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldDataNasc1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanel3.add(jFormattedTextFieldDataNasc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 90, -1));

        jFormattedTextFieldCpfCnpj1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        jFormattedTextFieldCpfCnpj1.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldCpfCnpj1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanel3.add(jFormattedTextFieldCpfCnpj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 90, -1));

        try {
            jFormattedTextFieldTelComecial1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelComecial1.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldTelComecial1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanel3.add(jFormattedTextFieldTelComecial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 140, -1));

        try {
            jFormattedTextFieldTelefonePessoal1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefonePessoal1.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldTelefonePessoal1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanel3.add(jFormattedTextFieldTelefonePessoal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 140, -1));

        try {
            jFormattedTextFieldCelularHum1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelularHum1.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldCelularHum1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanel3.add(jFormattedTextFieldCelularHum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 150, -1));

        jRadioButtonMasculino1.setText("Masculino");
        jPanel3.add(jRadioButtonMasculino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabelSexo1.setText("Sexo:");
        jPanel3.add(jLabelSexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jRadioButtonFeminino1.setText("Feminino");
        jPanel3.add(jRadioButtonFeminino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        try {
            jFormattedTextFieldDataCadastro1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataCadastro1.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldDataCadastro1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanel3.add(jFormattedTextFieldDataCadastro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 100, -1));

        jLabelNome2.setText("Nome: ");
        jPanel3.add(jLabelNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        jButtonPesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisa.png"))); // NOI18N
        jButtonPesquisar1.setToolTipText("Pesquisar Cliente");
        jButtonPesquisar1.setMaximumSize(new java.awt.Dimension(42, 28));
        jButtonPesquisar1.setMinimumSize(new java.awt.Dimension(42, 28));
        jButtonPesquisar1.setPreferredSize(new java.awt.Dimension(42, 28));
        jButtonPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisar1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPesquisar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 40, 30));

        jTextFieldEmailEmail1.setMaximumSize(new java.awt.Dimension(42, 28));
        jTextFieldEmailEmail1.setMinimumSize(new java.awt.Dimension(42, 28));
        jTextFieldEmailEmail1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanel3.add(jTextFieldEmailEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 380, -1));

        jLabelEmail3.setText("Email: ");
        jPanel3.add(jLabelEmail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jFormattedTextFieldCpfCnpj2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        jFormattedTextFieldCpfCnpj2.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldCpfCnpj2.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanel3.add(jFormattedTextFieldCpfCnpj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 160, -1));

        jTabbedPaneDadosCliente1.addTab("Pessoal", jPanel3);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelEndereco1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelEndereco1.setToolTipText("");
        jPanelEndereco1.setInheritsPopupMenu(true);
        jPanelEndereco1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxCidade1.setMaximumSize(new java.awt.Dimension(42, 28));
        jComboBoxCidade1.setMinimumSize(new java.awt.Dimension(42, 28));
        jComboBoxCidade1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanelEndereco1.add(jComboBoxCidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 170, -1));

        jLabel18.setText("Cidade:");
        jPanelEndereco1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jTextFieldComplemento1.setMaximumSize(new java.awt.Dimension(42, 28));
        jTextFieldComplemento1.setMinimumSize(new java.awt.Dimension(42, 28));
        jTextFieldComplemento1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanelEndereco1.add(jTextFieldComplemento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 170, -1));

        jTextFieldLogradouro1.setMaximumSize(new java.awt.Dimension(42, 28));
        jTextFieldLogradouro1.setMinimumSize(new java.awt.Dimension(42, 28));
        jTextFieldLogradouro1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanelEndereco1.add(jTextFieldLogradouro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 360, -1));

        jLabel16.setText("Bairro:");
        jPanelEndereco1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 20));

        jLabelTipoLogradouro1.setText("Tipo Logradouro:");
        jPanelEndereco1.add(jLabelTipoLogradouro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, 20));

        jTextFieldBairro1.setMaximumSize(new java.awt.Dimension(42, 28));
        jTextFieldBairro1.setMinimumSize(new java.awt.Dimension(42, 28));
        jTextFieldBairro1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanelEndereco1.add(jTextFieldBairro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 320, -1));

        jLabel21.setText("Cep:");
        jPanelEndereco1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 20));

        jLabel19.setText("Logradouro:");
        jPanelEndereco1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jLabel40.setText("Nº:");
        jPanelEndereco1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, 20));

        jLabel41.setText("Complemento:");
        jPanelEndereco1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel22.setText("UF:");
        jPanelEndereco1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        jComboBoxTipoLogradouro1.setMinimumSize(new java.awt.Dimension(42, 28));
        jComboBoxTipoLogradouro1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanelEndereco1.add(jComboBoxTipoLogradouro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 180, 30));

        jComboBoxUf1.setMinimumSize(new java.awt.Dimension(42, 28));
        jComboBoxUf1.setPreferredSize(new java.awt.Dimension(42, 28));
        jComboBoxUf1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxUf1ItemStateChanged(evt);
            }
        });
        jComboBoxUf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUf1ActionPerformed(evt);
            }
        });
        jPanelEndereco1.add(jComboBoxUf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 50, 30));

        try {
            jFormattedTextFieldCep1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##### ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCep1.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldCep1.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanelEndereco1.add(jFormattedTextFieldCep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 160, 30));

        jPanel5.add(jPanelEndereco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        jTabbedPaneDadosCliente1.addTab("Endereço", jPanel5);

        jPanelEndereco3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelEndereco3.setToolTipText("");
        jPanelEndereco3.setInheritsPopupMenu(true);
        jPanelEndereco3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTipoLogradouro2.setText("Tipo Logradouro:");
        jPanelEndereco3.add(jLabelTipoLogradouro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, 20));

        jComboBoxTipoLogradouro2.setMinimumSize(new java.awt.Dimension(42, 28));
        jComboBoxTipoLogradouro2.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanelEndereco3.add(jComboBoxTipoLogradouro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 180, 30));

        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });
        jPanelEndereco3.add(list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 340, -1));

        jTabbedPaneDadosCliente1.addTab("Veículo", jPanelEndereco3);

        jTabbedPaneDadosCliente.addTab("Dados do Cliente", jTabbedPaneDadosCliente1);

        jPanelEndereco2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelEndereco2.setToolTipText("");
        jPanelEndereco2.setInheritsPopupMenu(true);
        jPanelEndereco2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldComplemento2.setMaximumSize(new java.awt.Dimension(42, 28));
        jTextFieldComplemento2.setMinimumSize(new java.awt.Dimension(42, 28));
        jTextFieldComplemento2.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanelEndereco2.add(jTextFieldComplemento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 170, -1));

        jLabel24.setText("Senha:");
        jPanelEndereco2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, 20));

        jTextFieldBairro2.setMaximumSize(new java.awt.Dimension(42, 28));
        jTextFieldBairro2.setMinimumSize(new java.awt.Dimension(42, 28));
        jTextFieldBairro2.setPreferredSize(new java.awt.Dimension(42, 28));
        jPanelEndereco2.add(jTextFieldBairro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 170, -1));

        jLabel43.setText("Login (WEB):");
        jPanelEndereco2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jTabbedPaneDadosCliente.addTab("Dados do Sistema", jPanelEndereco2);

        jPanel1.add(jTabbedPaneDadosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 640, 460));

        jButtonIncluirPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/incluir.png"))); // NOI18N
        jButtonIncluirPF.setText("Incluir");
        jButtonIncluirPF.setToolTipText("incluir cliente pessoa FISICA");
        jButtonIncluirPF.setMaximumSize(new java.awt.Dimension(79, 25));
        jButtonIncluirPF.setMinimumSize(new java.awt.Dimension(79, 25));
        jButtonIncluirPF.setPreferredSize(new java.awt.Dimension(79, 25));
        jButtonIncluirPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirPFActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIncluirPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 110, 30));

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setMaximumSize(new java.awt.Dimension(79, 25));
        jButtonCancelar.setMinimumSize(new java.awt.Dimension(79, 25));
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(79, 25));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 120, 30));

        jButtonSair.setText("Sair");
        jButtonSair.setMaximumSize(new java.awt.Dimension(79, 25));
        jButtonSair.setMinimumSize(new java.awt.Dimension(79, 25));
        jButtonSair.setPreferredSize(new java.awt.Dimension(79, 25));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 120, 30));

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setMaximumSize(new java.awt.Dimension(79, 25));
        jButtonExcluir.setMinimumSize(new java.awt.Dimension(79, 25));
        jButtonExcluir.setPreferredSize(new java.awt.Dimension(79, 25));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 110, 30));

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/alterar.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setMaximumSize(new java.awt.Dimension(79, 25));
        jButtonAlterar.setMinimumSize(new java.awt.Dimension(79, 25));
        jButtonAlterar.setPreferredSize(new java.awt.Dimension(79, 25));
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 110, 30));

        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/gravar.png"))); // NOI18N
        jButtonGravar.setText("Gravar");
        jButtonGravar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonGravar.setMaximumSize(new java.awt.Dimension(79, 25));
        jButtonGravar.setMinimumSize(new java.awt.Dimension(79, 25));
        jButtonGravar.setPreferredSize(new java.awt.Dimension(79, 25));
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 110, 30));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 800, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 550, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 550, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisar1ActionPerformed

    private void jComboBoxUf1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxUf1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUf1ItemStateChanged

    private void jComboBoxUf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUf1ActionPerformed

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list1ActionPerformed

    private void jButtonIncluirPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirPFActionPerformed
        // TODO add your handling code here://
    }//GEN-LAST:event_jButtonIncluirPFActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO9 add your handling code here:
      //  dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        // TODO add your handling code here:
        }
    }//GEN-LAST:event_jButtonGravarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonIncluirPF;
    private javax.swing.JButton jButtonPesquisar1;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxCidade1;
    private javax.swing.JComboBox jComboBoxTipoLogradouro1;
    private javax.swing.JComboBox jComboBoxTipoLogradouro2;
    private javax.swing.JComboBox jComboBoxUf1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelularHum1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfCnpj1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfCnpj2;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataCadastro1;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNasc1;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelComecial1;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefonePessoal1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabelCel4;
    private javax.swing.JLabel jLabelCodigo1;
    private javax.swing.JLabel jLabelCpfCnpj1;
    private javax.swing.JLabel jLabelData1;
    private javax.swing.JLabel jLabelDataNasc1;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelEmail3;
    private javax.swing.JLabel jLabelNome2;
    private javax.swing.JLabel jLabelSexo1;
    private javax.swing.JLabel jLabelTelPessoal1;
    private javax.swing.JLabel jLabelTipoLogradouro1;
    private javax.swing.JLabel jLabelTipoLogradouro2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelEndereco1;
    private javax.swing.JPanel jPanelEndereco2;
    private javax.swing.JPanel jPanelEndereco3;
    private javax.swing.JRadioButton jRadioButtonFeminino1;
    private javax.swing.JRadioButton jRadioButtonMasculino1;
    private javax.swing.JTabbedPane jTabbedPaneDadosCliente;
    private javax.swing.JTabbedPane jTabbedPaneDadosCliente1;
    private javax.swing.JTextField jTextFieldBairro1;
    private javax.swing.JTextField jTextFieldBairro2;
    private javax.swing.JTextField jTextFieldComplemento1;
    private javax.swing.JTextField jTextFieldComplemento2;
    private javax.swing.JTextField jTextFieldEmailEmail1;
    private javax.swing.JTextField jTextFieldLogradouro1;
    private javax.swing.JTextField jTextFieldNome1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables

