/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cwsmanager.model.telas;

import br.edu.utfpr.cwsmanager.model.daos.DaoGenerics;
import br.edu.utfpr.cwsmanager.model.daos.TransactionManager;
import br.edu.utfpr.cwsmanager.model.endereco.Cidade;
import br.edu.utfpr.cwsmanager.model.pessoa.Cliente;
import br.edu.utfpr.cwsmanager.model.util.UtilDatas;
import br.edu.utfpr.cwsmanager.model.veiculo.Veiculo;
import br.edu.utfpr.cwsmanager.model.util.Validacao;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.awt.WindowClosingListener;

/**
 *
 * @author EduardoGreco
 */
public class JDialogCliente extends javax.swing.JDialog {

    private UtilDatas converteData = new UtilDatas();
    private DefaultTableModel modeloVeiculo;
    private List<Veiculo> veiculos = new ArrayList<Veiculo>();
    private Cliente cliente;
    private Cidade cidade;
    private Validacao validacao;

    /**
     * Creates new form JDialogCliente
     */
    public JDialogCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        habilitaCampos(false);

        modeloVeiculo = (DefaultTableModel) jTableVeiculo.getModel(); //cadastro veiculo
        modeloVeiculo.setNumRows(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupSexo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelCodCliente = new javax.swing.JLabel();
        jLabelNomeCliente = new javax.swing.JLabel();
        jLabelCpfCliente = new javax.swing.JLabel();
        jLabelSexoCliente = new javax.swing.JLabel();
        jRadioButtonMasculinoCliente = new javax.swing.JRadioButton();
        jRadioButtonFemininoCliente = new javax.swing.JRadioButton();
        jLabelDataNascCliente = new javax.swing.JLabel();
        jLabelTelPessoalCliente = new javax.swing.JLabel();
        jLabelTelComercialCliente = new javax.swing.JLabel();
        jLabelEmailCliente = new javax.swing.JLabel();
        jTextFieldIdCliente = new javax.swing.JTextField();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jFormattedTextFieldCPFCliente = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefonePessoalCliente = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataNascCliente = new javax.swing.JFormattedTextField();
        jTextFieldEmailCliente = new javax.swing.JTextField();
        jButtonPesquisarCliente = new javax.swing.JButton();
        jLabelCelCliente = new javax.swing.JLabel();
        jFormattedTextFieldCelularCliente = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelComecialCliente = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNomeEndereco = new javax.swing.JLabel();
        jTextFieldNomeEndreco = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldNumEndereco = new javax.swing.JTextField();
        jLabelComplemento = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jLabelCidadeEnd = new javax.swing.JLabel();
        jLabelCep = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldPesquisaCodCidade = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButtonPesquisarCidade = new javax.swing.JButton();
        jButtonIncluirCidade = new javax.swing.JButton();
        jTextFieldNomeCidade = new javax.swing.JTextField();
        jTextFieldUFCidade = new javax.swing.JTextField();
        jTextFieldCep = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextFieldPlaca = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldCor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxTipoVeiculo = new javax.swing.JComboBox();
        jButtonAdicionarVeiculo = new javax.swing.JButton();
        jButtonAlterarVeiculo = new javax.swing.JButton();
        jButtonExcluirVeiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeiculo = new javax.swing.JTable();
        jTextFieldIdVeiculo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldLoginCliente = new javax.swing.JTextField();
        jTextFieldSenhaCliente = new javax.swing.JTextField();
        jButtonGravar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");

        jLabelCodCliente.setText("Código:");

        jLabelNomeCliente.setText("Nome:*");

        jLabelCpfCliente.setText("CPF:*");

        jLabelSexoCliente.setText("Sexo:");

        GroupSexo.add(jRadioButtonMasculinoCliente);
        jRadioButtonMasculinoCliente.setText("Masculino");
        jRadioButtonMasculinoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMasculinoClienteActionPerformed(evt);
            }
        });

        GroupSexo.add(jRadioButtonFemininoCliente);
        jRadioButtonFemininoCliente.setText("Feminino");

        jLabelDataNascCliente.setText("Data de Nascimento:*");

        jLabelTelPessoalCliente.setText("Telefone Pessoal:*");

        jLabelTelComercialCliente.setText("Telefone Comercial:");

        jLabelEmailCliente.setText("Email:");

        jTextFieldIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdClienteActionPerformed(evt);
            }
        });

        jTextFieldNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeClienteActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCPFCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPFCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCPFClienteFocusLost(evt);
            }
        });

        try {
            jFormattedTextFieldTelefonePessoalCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefonePessoalCliente.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldTelefonePessoalCliente.setPreferredSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldTelefonePessoalCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelefonePessoalClienteActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDataNascCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataNascCliente.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldDataNascCliente.setPreferredSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldDataNascCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataNascClienteActionPerformed(evt);
            }
        });

        jTextFieldEmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailClienteActionPerformed(evt);
            }
        });
        jTextFieldEmailCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailClienteFocusLost(evt);
            }
        });

        jButtonPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisa.png"))); // NOI18N
        jButtonPesquisarCliente.setToolTipText("Pesquisar Cliente");
        jButtonPesquisarCliente.setMaximumSize(new java.awt.Dimension(42, 28));
        jButtonPesquisarCliente.setMinimumSize(new java.awt.Dimension(42, 28));
        jButtonPesquisarCliente.setPreferredSize(new java.awt.Dimension(42, 28));
        jButtonPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarClienteActionPerformed(evt);
            }
        });

        jLabelCelCliente.setText("Celular:");

        try {
            jFormattedTextFieldCelularCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelularCliente.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldCelularCliente.setPreferredSize(new java.awt.Dimension(42, 28));

        try {
            jFormattedTextFieldTelComecialCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelComecialCliente.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldTelComecialCliente.setPreferredSize(new java.awt.Dimension(42, 28));

        jLabel2.setText("* Campos Obrigatórios");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jLabelTelComercialCliente)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .add(jLabelEmailCliente)
                                        .add(99, 99, 99)))
                                .add(jTextFieldEmailCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 399, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabelCodCliente)
                                    .add(jLabelNomeCliente)
                                    .add(jLabelCpfCliente)
                                    .add(jLabelSexoCliente))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jRadioButtonMasculinoCliente)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jRadioButtonFemininoCliente))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jTextFieldIdCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jButtonPesquisarCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jTextFieldNomeCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 469, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jFormattedTextFieldCPFCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(157, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jFormattedTextFieldTelComecialCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                    .add(jLabelDataNascCliente)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jFormattedTextFieldDataNascCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(jLabelTelPessoalCliente)
                                    .add(28, 28, 28)
                                    .add(jFormattedTextFieldTelefonePessoalCliente, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .add(51, 51, 51)
                        .add(jLabelCelCliente)
                        .add(18, 18, 18)
                        .add(jFormattedTextFieldCelularCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabelCodCliente)
                        .add(jTextFieldIdCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jButtonPesquisarCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNomeCliente)
                    .add(jTextFieldNomeCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelCpfCliente)
                    .add(jFormattedTextFieldCPFCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelSexoCliente)
                    .add(jRadioButtonMasculinoCliente)
                    .add(jRadioButtonFemininoCliente))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelDataNascCliente)
                    .add(jFormattedTextFieldDataNascCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelTelPessoalCliente)
                    .add(jFormattedTextFieldTelefonePessoalCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelCelCliente)
                    .add(jFormattedTextFieldCelularCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelTelComercialCliente)
                    .add(jFormattedTextFieldTelComecialCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEmailCliente)
                    .add(jTextFieldEmailCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 65, Short.MAX_VALUE)
                .add(jLabel2))
        );

        jTabbedPane1.addTab("Pessoal", jPanel1);

        jLabelNomeEndereco.setText("Endereço:*");

        jLabel17.setText("Nº");

        jLabelComplemento.setText("Complemento:");

        jLabelBairro.setText("Bairro:*");

        jLabelCidadeEnd.setText("Cidade:*");

        jLabelCep.setText("CEP:*");

        jTextFieldPesquisaCodCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaCodCidadeActionPerformed(evt);
            }
        });
        jTextFieldPesquisaCodCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPesquisaCodCidadeFocusLost(evt);
            }
        });

        jLabel22.setText("UF:*");

        jButtonPesquisarCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisa.png"))); // NOI18N
        jButtonPesquisarCidade.setToolTipText("Pesquisar Cidade");
        jButtonPesquisarCidade.setMaximumSize(new java.awt.Dimension(42, 28));
        jButtonPesquisarCidade.setMinimumSize(new java.awt.Dimension(42, 28));
        jButtonPesquisarCidade.setPreferredSize(new java.awt.Dimension(42, 28));
        jButtonPesquisarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCidadeActionPerformed(evt);
            }
        });

        jButtonIncluirCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/incluir.png"))); // NOI18N
        jButtonIncluirCidade.setToolTipText("Pesquisar Cliente");
        jButtonIncluirCidade.setMaximumSize(new java.awt.Dimension(42, 28));
        jButtonIncluirCidade.setMinimumSize(new java.awt.Dimension(42, 28));
        jButtonIncluirCidade.setPreferredSize(new java.awt.Dimension(42, 28));
        jButtonIncluirCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirCidadeActionPerformed(evt);
            }
        });

        jTextFieldNomeCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCidadeActionPerformed(evt);
            }
        });

        try {
            jTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("* Campos Obrigatórios");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelNomeEndereco)
                    .add(jLabelComplemento)
                    .add(jLabelBairro)
                    .add(jLabelCidadeEnd)
                    .add(jLabelCep))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jTextFieldNomeEndreco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 338, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel17)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextFieldNumEndereco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextFieldBairro)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextFieldComplemento)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                                .add(jTextFieldPesquisaCodCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonPesquisarCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonIncluirCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 119, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextFieldNomeCidade))
                        .add(18, 18, 18)
                        .add(jLabel22)
                        .add(18, 18, 18)
                        .add(jTextFieldUFCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jTextFieldCep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 265, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(jLabel3)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNomeEndereco)
                    .add(jTextFieldNomeEndreco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel17)
                    .add(jTextFieldNumEndereco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelComplemento)
                    .add(jTextFieldComplemento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelBairro)
                    .add(jTextFieldBairro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabelCidadeEnd)
                        .add(jTextFieldPesquisaCodCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jButtonPesquisarCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonIncluirCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldNomeCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel22)
                    .add(jTextFieldUFCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(20, 20, 20)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelCep)
                    .add(jTextFieldCep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 141, Short.MAX_VALUE)
                .add(jLabel3))
        );

        jTabbedPane1.addTab("Endereço", jPanel2);

        jLabel12.setText("Placa:");

        jFormattedTextFieldPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPlacaActionPerformed(evt);
            }
        });

        jLabel13.setText("Modelo:");

        jLabel14.setText("Cor:");

        jLabel15.setText("Tipo do Veículo:*");

        jComboBoxTipoVeiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carro", "Caminhao", "Caminhonete", "Moto", "Onibus" }));

        jButtonAdicionarVeiculo.setText("Adicionar");
        jButtonAdicionarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarVeiculoActionPerformed(evt);
            }
        });

        jButtonAlterarVeiculo.setText("Alterar");
        jButtonAlterarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarVeiculoActionPerformed(evt);
            }
        });

        jButtonExcluirVeiculo.setText("Excluir");
        jButtonExcluirVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirVeiculoActionPerformed(evt);
            }
        });

        jTableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Placa", "Modelo", "Cor", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVeiculo);

        jTextFieldIdVeiculo.setEditable(false);

        jLabel1.setText("Cód.:");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(49, 49, 49)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 564, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jLabel15)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jComboBoxTipoVeiculo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel14)
                                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel13)
                                            .add(jLabel12))
                                        .add(jLabel1)))
                                .add(18, 18, 18)
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jTextFieldCor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .add(jFormattedTextFieldPlaca, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .add(jTextFieldModelo)
                                    .add(jTextFieldIdVeiculo))))
                        .add(34, 34, 34)
                        .add(jButtonAdicionarVeiculo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonAlterarVeiculo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonExcluirVeiculo)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldIdVeiculo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(12, 12, 12)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel13)
                            .add(jTextFieldModelo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(12, 12, 12)
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel14)
                                    .add(jTextFieldCor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(58, 58, 58)
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jButtonExcluirVeiculo)
                                    .add(jButtonAlterarVeiculo)
                                    .add(jButtonAdicionarVeiculo)
                                    .add(jComboBoxTipoVeiculo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel15))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel12)
                        .add(jFormattedTextFieldPlaca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Veículo", jPanel3);

        jLabel10.setText("Login:");

        jLabel11.setText("Senha:");

        jTextFieldLoginCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginClienteActionPerformed(evt);
            }
        });

        jTextFieldSenhaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSenhaClienteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(45, 45, 45)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel10)
                    .add(jLabel11))
                .add(38, 38, 38)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextFieldLoginCliente)
                    .add(jTextFieldSenhaCliente, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(jTextFieldLoginCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(jTextFieldSenhaCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(350, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login WebSite", jPanel4);

        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/gravar.png"))); // NOI18N
        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/remove.png"))); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/incluir.png"))); // NOI18N
        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/alterar.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        jButtonExcluir.setText("Exluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jButtonIncluir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonAlterar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonExcluir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(86, 86, 86)
                        .add(jButtonGravar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonCancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 748, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 495, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jButtonIncluir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonAlterar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonExcluir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonCancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonGravar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMasculinoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMasculinoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMasculinoClienteActionPerformed

    private void jTextFieldNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeClienteActionPerformed

    private void jFormattedTextFieldTelefonePessoalClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefonePessoalClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTelefonePessoalClienteActionPerformed

    private void jFormattedTextFieldDataNascClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataNascClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataNascClienteActionPerformed

    private void jButtonPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarClienteActionPerformed

        final JDialogConsCliente consulta = new JDialogConsCliente(this, true);
        consulta.setLocationRelativeTo(consulta);
        consulta.setVisible(true);

        consulta.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cliente = consulta.cliente;
                try {
                    TransactionManager.beginTransaction();
                    cliente = new DaoGenerics<Cliente>(Cliente.class).retrieve(cliente.getId());
                    TransactionManager.commit();
                } catch (Exception ex) {
                    Logger.getLogger(JDialogCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                setCliente();

                habilitaCampos(true);
                jTextFieldIdCliente.setEnabled(false);
                jTextFieldIdVeiculo.setEnabled(false);
                jButtonPesquisarCliente.setEnabled(true);
            }
        });
    }//GEN-LAST:event_jButtonPesquisarClienteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonIncluir.setEnabled(false);

        jButtonCancelar.setEnabled(true);
        jButtonGravar.setEnabled(true);

        jTextFieldIdCliente.setEnabled(false);
        jButtonPesquisarCliente.setEnabled(false);
        jTextFieldNomeCliente.setEnabled(true);
        jFormattedTextFieldCPFCliente.setEnabled(true);
        jRadioButtonMasculinoCliente.setEnabled(true);
        jRadioButtonFemininoCliente.setEnabled(true);
        jFormattedTextFieldDataNascCliente.setEnabled(true);
        jFormattedTextFieldTelefonePessoalCliente.setEnabled(true);
        jFormattedTextFieldCelularCliente.setEnabled(true);
        jFormattedTextFieldTelComecialCliente.setEnabled(true);
        jTextFieldEmailCliente.setEnabled(true);
        jTextFieldLoginCliente.setEnabled(true);
        jTextFieldSenhaCliente.setEnabled(true);
        jTextFieldNomeEndreco.setEnabled(true);
        jTextFieldNumEndereco.setEnabled(true);
        jTextFieldComplemento.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldPesquisaCodCidade.setEnabled(true);
        jButtonPesquisarCidade.setEnabled(true);
        jButtonIncluirCidade.setEnabled(true);
        jTextFieldNomeCidade.setEnabled(true);
        jTextFieldUFCidade.setEnabled(true);
        jTextFieldCep.setEnabled(true);

        jTextFieldIdVeiculo.setEnabled(false);
        jFormattedTextFieldPlaca.setEnabled(true);
        jTextFieldModelo.setEnabled(true);
        jTextFieldCor.setEnabled(true);
        jComboBoxTipoVeiculo.setEnabled(true);
        jTableVeiculo.setEnabled(true);
        jButtonAdicionarVeiculo.setEnabled(true);
        jButtonAlterarVeiculo.setEnabled(true);
        jButtonExcluirVeiculo.setEnabled(true);

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        String[] opcoes = {"Sim", "Não"};
        int opcao = JOptionPane.showOptionDialog(null, "Tem certeza que deseja excluir?", "Confirmação",
                JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[1]);

        if (JOptionPane.OK_OPTION == opcao) {
            try {
                TransactionManager.beginTransaction();
                DaoGenerics<Cliente> daoCliente = new DaoGenerics<>(Cliente.class);
                daoCliente.delete(daoCliente.retrieve(Integer.parseInt(jTextFieldIdCliente.getText())));
                JOptionPane.showMessageDialog(null, "O registro foi excluido com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                TransactionManager.commit();
            } catch (Exception ex) {
                TransactionManager.rollback();
                Logger.getLogger(JDialogCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        clearCampos();


    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        clearCampos();
        habilitaCampos(false);
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jTextFieldLoginClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginClienteActionPerformed

    private void jTextFieldSenhaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSenhaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSenhaClienteActionPerformed

    private void jFormattedTextFieldPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPlacaActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        // TODO add your handling code here:
        if (!validaCampos()) {
            return;
        }
        try {
            gravar();
        } catch (Exception ex) {
   //         JOptionPane.showMessageDialog(null, ex.getMessage());
            Logger.getLogger(JDialogCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Registro gravado com sucesso.", "Gravar", JOptionPane.INFORMATION_MESSAGE);

        habilitaCampos(true);
        jButtonPesquisarCliente.setEnabled(true);
        jTextFieldIdVeiculo.setEnabled(false);
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        try {
            TransactionManager.rollback();
        } catch (Exception e) {
        }
        habilitaCampos(true);
        jTextFieldIdVeiculo.setEnabled(false);
        clearCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonPesquisarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCidadeActionPerformed
        final JDialogConsCidade consultaCidade = new JDialogConsCidade(this, true);
        consultaCidade.setLocationRelativeTo(consultaCidade);
        consultaCidade.setVisible(true);


        consultaCidade.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cidade = consultaCidade.cidade;

                try {
                    TransactionManager.beginTransaction();
                    cidade = new DaoGenerics<Cidade>(Cidade.class).retrieve(cidade.getId());
                    TransactionManager.commit();
                } catch (Exception ex) {
                    Logger.getLogger(JDialogCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                jTextFieldPesquisaCodCidade.setText(Integer.toString(cidade.getId()));
                jTextFieldNomeCidade.setText(cidade.getNome());
                jTextFieldUFCidade.setText(cidade.getEstado());

            }
        });

    }//GEN-LAST:event_jButtonPesquisarCidadeActionPerformed

    private void jButtonIncluirCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirCidadeActionPerformed
        // TODO add your handling code here:
        JDialogCidade cadCidade = new JDialogCidade(this, true);
         cadCidade.setLocationRelativeTo(cadCidade);
        cadCidade.setVisible(true);
    }//GEN-LAST:event_jButtonIncluirCidadeActionPerformed

    private void jButtonAdicionarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarVeiculoActionPerformed
        // TODO add your handling code here:
        Veiculo veiculo = new Veiculo();
        try {
            veiculo.setId(Integer.parseInt(jTextFieldIdVeiculo.getText().toString().trim()));
        } catch (Exception e) {
        }
        jTextFieldIdVeiculo.setText("");
        veiculo.setPlaca(jFormattedTextFieldPlaca.getText().trim());
        veiculo.setModelo(jTextFieldModelo.getText().trim());
        veiculo.setCor(jTextFieldCor.getText().trim());
        veiculo.setTipoVeiculo(jComboBoxTipoVeiculo.getSelectedItem().toString());

        veiculos.add(veiculo);
        preencherTableVeiculos();
    }//GEN-LAST:event_jButtonAdicionarVeiculoActionPerformed

    private void jButtonAlterarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarVeiculoActionPerformed
        // TODO add your handling code here:
        int linha = jTableVeiculo.getSelectedRow();

        if (linha < 0) {
            return;
        }

        jTextFieldIdVeiculo.setText(jTableVeiculo.getValueAt(linha, 0).toString());
        jFormattedTextFieldPlaca.setText(jTableVeiculo.getValueAt(linha, 1).toString());
        jTextFieldModelo.setText(jTableVeiculo.getValueAt(linha, 2).toString());
        jTextFieldCor.setText(jTableVeiculo.getValueAt(linha, 3).toString());
        jComboBoxTipoVeiculo.setSelectedItem(jTableVeiculo.getValueAt(linha, 4).toString());

        veiculos.remove(linha);
        preencherTableVeiculos();
    }//GEN-LAST:event_jButtonAlterarVeiculoActionPerformed

    private void jButtonExcluirVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirVeiculoActionPerformed
        // TODO add your handling code here:
        int linha = jTableVeiculo.getSelectedRow();

        if (linha < 0) {
            return;
        }

        Veiculo v = new Veiculo();

        v = veiculos.get(linha);

        if (v.getId() != 0) {
            try {
                TransactionManager.beginTransaction();
                new DaoGenerics<Veiculo>(Veiculo.class).delete(v);
                  TransactionManager.commit();
            } catch (Exception ex) {
                Logger.getLogger(JDialogCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        veiculos.remove(linha);
        preencherTableVeiculos();
    }//GEN-LAST:event_jButtonExcluirVeiculoActionPerformed

    private void jTextFieldPesquisaCodCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaCodCidadeFocusLost
        Cidade cidade = new Cidade();
        int id_cidade = 0;

        try {
            id_cidade = Integer.parseInt(jTextFieldPesquisaCodCidade.getText().trim());
        } catch (Exception e) {
            return;
        }

        try {
            //     cidade = daoCidade.retrieve(id_cidade);
            cidade = new DaoGenerics<Cidade>(Cidade.class).retrieve(id_cidade);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Código da cidade não cadastrado", "Atenção", JOptionPane.WARNING_MESSAGE);
            jTextFieldPesquisaCodCidade.setText("");
            jTextFieldPesquisaCodCidade.grabFocus();
            return;
        }

        jTextFieldNomeCidade.setText(cidade.getNome());
        jTextFieldUFCidade.setText(cidade.getEstado());
    }//GEN-LAST:event_jTextFieldPesquisaCodCidadeFocusLost

    private void jTextFieldIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdClienteActionPerformed

    private void jTextFieldNomeCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeCidadeActionPerformed

    private void jTextFieldPesquisaCodCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaCodCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaCodCidadeActionPerformed

    private void jTextFieldEmailClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailClienteFocusLost
    }//GEN-LAST:event_jTextFieldEmailClienteFocusLost

    private void jTextFieldEmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailClienteActionPerformed

    private void jFormattedTextFieldCPFClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFClienteFocusLost
        // TODO add your handling code here:
        if (!evt.isTemporary()) {
            if (!jFormattedTextFieldCPFCliente.getText().replaceAll("[ .\\-/()]", "").isEmpty()) {
                validacao = new Validacao();
                if (!validacao.validaCpf(jFormattedTextFieldCPFCliente.getText().trim())) {
                    JOptionPane.showMessageDialog(null, "CPF é inválido!", "Atençao!", JOptionPane.WARNING_MESSAGE);
                    jFormattedTextFieldCPFCliente.setText("");
                    jFormattedTextFieldCPFCliente.grabFocus();
                }
            }
        }
    }//GEN-LAST:event_jFormattedTextFieldCPFClienteFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCliente dialog = new JDialogCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupSexo;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdicionarVeiculo;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAlterarVeiculo;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonExcluirVeiculo;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonIncluirCidade;
    private javax.swing.JButton jButtonPesquisarCidade;
    private javax.swing.JButton jButtonPesquisarCliente;
    private javax.swing.JComboBox jComboBoxTipoVeiculo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPFCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelularCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldPlaca;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelComecialCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefonePessoalCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCelCliente;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidadeEnd;
    private javax.swing.JLabel jLabelCodCliente;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelCpfCliente;
    private javax.swing.JLabel jLabelDataNascCliente;
    private javax.swing.JLabel jLabelEmailCliente;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelNomeEndereco;
    private javax.swing.JLabel jLabelSexoCliente;
    private javax.swing.JLabel jLabelTelComercialCliente;
    private javax.swing.JLabel jLabelTelPessoalCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonFemininoCliente;
    private javax.swing.JRadioButton jRadioButtonMasculinoCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableVeiculo;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JFormattedTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldEmailCliente;
    private javax.swing.JTextField jTextFieldIdCliente;
    private javax.swing.JTextField jTextFieldIdVeiculo;
    private javax.swing.JTextField jTextFieldLoginCliente;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNomeCidade;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldNomeEndreco;
    private javax.swing.JTextField jTextFieldNumEndereco;
    private javax.swing.JTextField jTextFieldPesquisaCodCidade;
    private javax.swing.JTextField jTextFieldSenhaCliente;
    private javax.swing.JTextField jTextFieldUFCidade;
    // End of variables declaration//GEN-END:variables

    public void gravar() throws Exception {
        cliente = null;

        if (jTextFieldIdCliente.getText().isEmpty()) {
            cliente = new Cliente();
        } else {
            cliente = new DaoGenerics<Cliente>(Cliente.class).retrieve(Integer.parseInt(jTextFieldIdCliente.getText()));
        }
        TransactionManager.beginTransaction();
        cliente.setNome(jTextFieldNomeCliente.getText().trim());
        cliente.setCpf(jFormattedTextFieldCPFCliente.getText().trim());
        cliente.setSexo((jRadioButtonMasculinoCliente.isSelected()) ? "M" : "F");
        cliente.setDataNascimento(converteData.toDate(jFormattedTextFieldDataNascCliente.getText().trim()));
        cliente.setTelPessoal(jFormattedTextFieldTelefonePessoalCliente.getText().trim());
        cliente.setCelular(jFormattedTextFieldCelularCliente.getText().trim());
        cliente.setTelComercial(jFormattedTextFieldTelComecialCliente.getText().trim());
        cliente.setEmail(jTextFieldEmailCliente.getText().trim());
        cliente.setLogin(jTextFieldLoginCliente.getText().trim());
        cliente.setSenha(jTextFieldSenhaCliente.getText().trim());

        cliente.getEndereco().setNomeEndereco(jTextFieldNomeEndreco.getText().trim());
        cliente.getEndereco().setNumero(Integer.parseInt(jTextFieldNumEndereco.getText().trim()));
        cliente.getEndereco().setComplemento(jTextFieldComplemento.getText().trim());
        cliente.getEndereco().setBairro(jTextFieldBairro.getText().trim());
        //cliente.getEndereco().getCidade().setId(Integer.parseInt(jTextFieldPesquisaCodCidade.getText().trim()));
        cidade = new Cidade();
        cidade.setId(Integer.parseInt(jTextFieldPesquisaCodCidade.getText().trim()));
        cliente.getEndereco().setCidade(cidade);
        cliente.getEndereco().setCep(jTextFieldCep.getText().trim());

        cliente.setVeiculos(veiculos);

        new DaoGenerics<Cliente>(Cliente.class).persist(cliente);
        TransactionManager.commit();
    }

    private void setCliente() {
        jTextFieldIdCliente.setText(Integer.toString(cliente.getId()));
        jTextFieldNomeCliente.setText(cliente.getNome());
        jFormattedTextFieldCPFCliente.setText(cliente.getCpf());
        jRadioButtonMasculinoCliente.setSelected((cliente.getSexo().equals("M") ? true : false));
        jFormattedTextFieldDataNascCliente.setText(converteData.toString(cliente.getDataNascimento()));
        jFormattedTextFieldTelefonePessoalCliente.setText(cliente.getTelPessoal());
        jFormattedTextFieldCelularCliente.setText(cliente.getCelular());
        jFormattedTextFieldTelComecialCliente.setText(cliente.getTelComercial());
        jTextFieldEmailCliente.setText(cliente.getEmail());
        jTextFieldLoginCliente.setText(cliente.getLogin());
        jTextFieldSenhaCliente.setText(cliente.getSenha());

        jTextFieldNomeEndreco.setText(cliente.getEndereco().getNomeEndereco());
        jTextFieldNumEndereco.setText(Integer.toString(cliente.getEndereco().getNumero()));
        jTextFieldComplemento.setText(cliente.getEndereco().getComplemento());
        jTextFieldBairro.setText(cliente.getEndereco().getBairro());
        jTextFieldPesquisaCodCidade.setText(Integer.toString(cliente.getEndereco().getCidade().getId()));
        jTextFieldNomeCidade.setText(cliente.getEndereco().getCidade().getNome());
        jTextFieldUFCidade.setText(cliente.getEndereco().getCidade().getEstado());
        jTextFieldCep.setText(cliente.getEndereco().getCep());

        veiculos = cliente.getVeiculos();
        preencherTableVeiculos();
    }

    private void clearCampos() {
        cliente = new Cliente();
        jTextFieldIdCliente.setText("");
        jTextFieldNomeCliente.setText("");
        jFormattedTextFieldCPFCliente.setText("");
        jRadioButtonMasculinoCliente.setSelected(true);
        jFormattedTextFieldDataNascCliente.setText("");
        jFormattedTextFieldTelefonePessoalCliente.setText("");
        jFormattedTextFieldCelularCliente.setText("");
        jFormattedTextFieldTelComecialCliente.setText("");
        jTextFieldEmailCliente.setText("");
        jTextFieldLoginCliente.setText("");
        jTextFieldSenhaCliente.setText("");
        jTextFieldNomeEndreco.setText("");
        jTextFieldNumEndereco.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldBairro.setText("");
        jTextFieldPesquisaCodCidade.setText("");
        jTextFieldNomeCidade.setText("");
        jTextFieldUFCidade.setText("");
        jTextFieldCep.setText("");
        modeloVeiculo.setNumRows(0);
        veiculos.clear();

    }

    private void habilitaCampos(boolean comando) {
        jButtonAlterar.setEnabled(comando);
        jButtonExcluir.setEnabled(comando);
        jButtonIncluir.setEnabled(comando);

        jButtonCancelar.setEnabled(!comando);
        jButtonGravar.setEnabled(!comando);

        jTextFieldIdCliente.setEnabled(comando);
        jButtonPesquisarCliente.setEnabled(!comando);
        jTextFieldNomeCliente.setEnabled(!comando);
        jFormattedTextFieldCPFCliente.setEnabled(!comando);
        jRadioButtonMasculinoCliente.setEnabled(!comando);
        jRadioButtonFemininoCliente.setEnabled(!comando);
        jFormattedTextFieldDataNascCliente.setEnabled(!comando);
        jFormattedTextFieldTelefonePessoalCliente.setEnabled(!comando);
        jFormattedTextFieldCelularCliente.setEnabled(!comando);
        jFormattedTextFieldTelComecialCliente.setEnabled(!comando);
        jTextFieldEmailCliente.setEnabled(!comando);
        jTextFieldLoginCliente.setEnabled(!comando);
        jTextFieldSenhaCliente.setEnabled(!comando);
        jTextFieldNomeEndreco.setEnabled(!comando);
        jTextFieldNumEndereco.setEnabled(!comando);
        jTextFieldComplemento.setEnabled(!comando);
        jTextFieldBairro.setEnabled(!comando);
        jTextFieldPesquisaCodCidade.setEnabled(!comando);
        jButtonPesquisarCidade.setEnabled(!comando);
        jButtonIncluirCidade.setEnabled(!comando);
        jTextFieldNomeCidade.setEnabled(!comando);
        jTextFieldUFCidade.setEnabled(!comando);
        jTextFieldCep.setEnabled(!comando);

        jTextFieldIdVeiculo.setEnabled(comando);
        jFormattedTextFieldPlaca.setEnabled(!comando);
        jTextFieldModelo.setEnabled(!comando);
        jTextFieldCor.setEnabled(!comando);
        jComboBoxTipoVeiculo.setEnabled(!comando);
        jTableVeiculo.setEnabled(!comando);
        jButtonAdicionarVeiculo.setEnabled(!comando);
        jButtonAlterarVeiculo.setEnabled(!comando);
        jButtonExcluirVeiculo.setEnabled(!comando);

    }

    private void preencherTableVeiculos() {
        modeloVeiculo.setNumRows(0);
        for (Veiculo obj : veiculos) {
            modeloVeiculo.addRow(new Object[]{
                obj.getId(),
                obj.getPlaca(),
                obj.getModelo(),
                obj.getCor(),
                obj.getTipoVeiculo()
            });
        }
    }

    private boolean validaCampos() {
        if (jTextFieldNomeCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jTextFieldNomeCliente.grabFocus();
            return false;
        }
        if (jFormattedTextFieldCPFCliente.getText().replaceAll("[ .\\-/()]", "").isEmpty()) {
            JOptionPane.showMessageDialog(null, "CPF é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldCPFCliente.grabFocus();
            return false;
        }
        if (jFormattedTextFieldDataNascCliente.getText().replaceAll("[ /]", "").isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data de Nascimento é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldDataNascCliente.grabFocus();
            return false;
        }
        if (jFormattedTextFieldTelefonePessoalCliente.getText().replaceAll("[ ()-]", "").isEmpty()) {
            JOptionPane.showMessageDialog(null, "Telefone Pessoal é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldTelefonePessoalCliente.grabFocus();
            return false;
        }
        if (!jTextFieldEmailCliente.getText().isEmpty()) {
            validacao = new Validacao();
            if (!validacao.validarEmail(jTextFieldEmailCliente.getText().trim())) {
                JOptionPane.showMessageDialog(null, "Email nao é valido!", "Atençao!", JOptionPane.WARNING_MESSAGE);
                jTextFieldEmailCliente.grabFocus();
                return false;
            }
        }
        if (jTextFieldNomeEndreco.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Endereço é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jTextFieldNomeEndreco.grabFocus();
            return false;
        }
        if (jTextFieldNumEndereco.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Numero é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jTextFieldNumEndereco.grabFocus();
            return false;
        }
        if (jTextFieldBairro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bairro é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jTextFieldBairro.grabFocus();
            return false;
        }
        if (jTextFieldNomeCidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome da Cidade é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jTextFieldNomeCidade.grabFocus();
            return false;
        }
        if (jTextFieldCep.getText().replaceAll("[ -]", "").isEmpty()) {
            JOptionPane.showMessageDialog(null, "CEP é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jTextFieldCep.grabFocus();
            return false;
        }
        return true;
    }
}
