/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cwsmanager.model.telas;

import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author EduardoGreco
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jtAtalho = new javax.swing.JToolBar();
        jButtonCliente = new javax.swing.JButton();
        jButtonSolicitacaoService = new javax.swing.JButton();
        jButtonOrdemServicoMENU = new javax.swing.JButton();
        jButtonConsultaClienteMENU = new javax.swing.JButton();
        jButtonGerRelatorioMENU = new javax.swing.JButton();
        jButtonSobreMENU = new javax.swing.JButton();
        jButtonManualMENU = new javax.swing.JButton();
        jButtonSairMENU = new javax.swing.JButton();
        jButtonProduto = new javax.swing.JButton();
        jButtonCompra = new javax.swing.JButton();
        jButtonVenda = new javax.swing.JButton();
        jButtonHistoricoCliente = new javax.swing.JButton();
        jButtonEstoque = new javax.swing.JButton();
        jButtonGerRelatorio = new javax.swing.JButton();
        jButtonManual = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuSolicitacaoServico = new javax.swing.JMenu();
        jMenuOrdemServico = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItemConsultaCidade = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu8.setText("File");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("jMenu10");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtAtalho.setBackground(new java.awt.Color(198, 198, 198));
        jtAtalho.setRollover(true);

        jButtonCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pessoa.png"))); // NOI18N
        jButtonCliente.setToolTipText("Cadastrar Clientes");
        jButtonCliente.setFocusable(false);
        jButtonCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonClienteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonClienteMouseEntered(evt);
            }
        });
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonCliente);

        jButtonSolicitacaoService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ssservice.png"))); // NOI18N
        jButtonSolicitacaoService.setToolTipText("Solicitacao de Servico");
        jButtonSolicitacaoService.setFocusable(false);
        jButtonSolicitacaoService.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSolicitacaoService.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSolicitacaoService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSolicitacaoServiceMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSolicitacaoServiceMouseEntered(evt);
            }
        });
        jButtonSolicitacaoService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolicitacaoServiceActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonSolicitacaoService);

        jButtonOrdemServicoMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ordemservico.png"))); // NOI18N
        jButtonOrdemServicoMENU.setToolTipText("Ordem de Servico");
        jButtonOrdemServicoMENU.setFocusable(false);
        jButtonOrdemServicoMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOrdemServicoMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonOrdemServicoMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonOrdemServicoMENUMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonOrdemServicoMENUMouseEntered(evt);
            }
        });
        jButtonOrdemServicoMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdemServicoMENUActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonOrdemServicoMENU);

        jButtonConsultaClienteMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/search.png"))); // NOI18N
        jButtonConsultaClienteMENU.setToolTipText("Consulta de Clientes");
        jButtonConsultaClienteMENU.setFocusable(false);
        jButtonConsultaClienteMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConsultaClienteMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonConsultaClienteMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonConsultaClienteMENUMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonConsultaClienteMENUMouseEntered(evt);
            }
        });
        jButtonConsultaClienteMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaClienteMENUActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonConsultaClienteMENU);

        jButtonGerRelatorioMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/relatorios.png"))); // NOI18N
        jButtonGerRelatorioMENU.setToolTipText("Gerenciamento de Relatóriosl");
        jButtonGerRelatorioMENU.setFocusable(false);
        jButtonGerRelatorioMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGerRelatorioMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGerRelatorioMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonGerRelatorioMENUMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonGerRelatorioMENUMouseEntered(evt);
            }
        });
        jButtonGerRelatorioMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerRelatorioMENUActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonGerRelatorioMENU);

        jButtonSobreMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/help.png"))); // NOI18N
        jButtonSobreMENU.setToolTipText("Informação do Sistema");
        jButtonSobreMENU.setFocusable(false);
        jButtonSobreMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSobreMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSobreMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSobreMENUMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSobreMENUMouseEntered(evt);
            }
        });
        jButtonSobreMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreMENUActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonSobreMENU);

        jButtonManualMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/manual.png"))); // NOI18N
        jButtonManualMENU.setToolTipText("Manual do Usuário");
        jButtonManualMENU.setFocusable(false);
        jButtonManualMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonManualMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonManualMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonManualMENUMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonManualMENUMouseEntered(evt);
            }
        });
        jButtonManualMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManualMENUActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonManualMENU);

        jButtonSairMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/quit.png"))); // NOI18N
        jButtonSairMENU.setToolTipText("Sair do Sistema");
        jButtonSairMENU.setFocusable(false);
        jButtonSairMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSairMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSairMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSairMENUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSairMENUMouseExited(evt);
            }
        });
        jButtonSairMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairMENUActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonSairMENU);

        jButtonProduto.setToolTipText("Cadastro de Produtos");
        jButtonProduto.setFocusable(false);
        jButtonProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonProdutoMouseExited(evt);
            }
        });
        jButtonProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonProduto);

        jButtonCompra.setToolTipText("Registrar Compras");
        jButtonCompra.setFocusable(false);
        jButtonCompra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCompra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCompraMouseExited(evt);
            }
        });
        jButtonCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompraActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonCompra);

        jButtonVenda.setToolTipText("Registrar Vendas");
        jButtonVenda.setFocusable(false);
        jButtonVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVendaMouseExited(evt);
            }
        });
        jButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendaActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonVenda);

        jButtonHistoricoCliente.setToolTipText("Histórico de Clientes");
        jButtonHistoricoCliente.setFocusable(false);
        jButtonHistoricoCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHistoricoCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonHistoricoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonHistoricoClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonHistoricoClienteMouseExited(evt);
            }
        });
        jButtonHistoricoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoricoClienteActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonHistoricoCliente);

        jButtonEstoque.setToolTipText("Verificar Estoque");
        jButtonEstoque.setFocusable(false);
        jButtonEstoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEstoque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEstoqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEstoqueMouseExited(evt);
            }
        });
        jButtonEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstoqueActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonEstoque);

        jButtonGerRelatorio.setToolTipText("Gerenciamento de Relatóriosl");
        jButtonGerRelatorio.setFocusable(false);
        jButtonGerRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGerRelatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGerRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonGerRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonGerRelatorioMouseExited(evt);
            }
        });
        jButtonGerRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerRelatorioActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonGerRelatorio);

        jButtonManual.setToolTipText("Manual do Usuário");
        jButtonManual.setFocusable(false);
        jButtonManual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonManual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonManualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonManualMouseExited(evt);
            }
        });
        jButtonManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManualActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonManual);

        jButtonSair.setToolTipText("Sair do Sistema");
        jButtonSair.setFocusable(false);
        jButtonSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSairMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSairMouseEntered(evt);
            }
        });
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jtAtalho.add(jButtonSair);

        jMenuCadastros.setText("Cadastros");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/funcionario.png"))); // NOI18N
        jMenuItem1.setText("Cadastrar Funcionário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItem1);

        jMenuCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/client.png"))); // NOI18N
        jMenuCadastro.setText("Cadastrar Cliente");
        jMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuCadastro);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Cadastrar Tipo de Serviço");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItem3);

        jMenuItem18.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/city.png"))); // NOI18N
        jMenuItem18.setText("Cadastrar Cidade");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItem18);

        jMenuBar1.add(jMenuCadastros);

        jMenuSolicitacaoServico.setText("Solicitação de Serviço");
        jMenuBar1.add(jMenuSolicitacaoServico);

        jMenuOrdemServico.setText("Ordem de Serviço");
        jMenuBar1.add(jMenuOrdemServico);

        jMenu4.setText("Consultas");

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/searchfuncionario.png"))); // NOI18N
        jMenuItem15.setText("Consulta de Funcionários");
        jMenu4.add(jMenuItem15);

        jMenuItemConsultaCidade.setText("Consulta de Cidades");
        jMenu4.add(jMenuItemConsultaCidade);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/searchclient.png"))); // NOI18N
        jMenuItem17.setText("Consulta de Clientes");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem17);

        jMenuItem2.setText("Consulta de Tipo de Servico");
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Relatórios");

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/gerenciarRel.png"))); // NOI18N
        jMenuItem14.setText("Gerenciador de relatórios");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Ferramentas");

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/bancoDeDados.png"))); // NOI18N
        jMenuItem12.setText("Configuração do Banco de dados");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/consultaHQL.png"))); // NOI18N
        jMenuItem13.setText("Consulta HQL");
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Sobre");

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sobre.png"))); // NOI18N
        jMenuItem11.setText("Informações");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ajuda");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/manual_menu.png"))); // NOI18N
        jMenuItem8.setText("Manual Web");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/manual_mer.png"))); // NOI18N
        jMenuItem9.setText("Figura do Modelo do Banco de Dados");
        jMenu6.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/especificacao.png"))); // NOI18N
        jMenuItem10.setText("Especificação do projeto");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Opções");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logout.png"))); // NOI18N
        jMenuItem6.setText("Logout");
        jMenu7.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        jMenuItem7.setText("Sair");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jtAtalho, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jtAtalho, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 568, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroActionPerformed
        JDialogCliente jdCliente = new JDialogCliente(this, true);
        jdCliente.setLocationRelativeTo(null);
        jdCliente.setVisible(true);
    }//GEN-LAST:event_jMenuCadastroActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JDialogTipoServico jdTipoServico = new JDialogTipoServico(this, true);
        jdTipoServico.setLocationRelativeTo(null);
        jdTipoServico.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButtonClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClienteMouseEntered

    private void jButtonClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClienteMouseExited

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        // TODO add your handling code here:
        JDialogCliente jdCliente = new JDialogCliente(this, true);
        jdCliente.setLocationRelativeTo(jdCliente);
        jdCliente.setVisible(true);
    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jButtonProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProdutoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProdutoMouseEntered

    private void jButtonProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProdutoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProdutoMouseExited

    private void jButtonProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProdutoActionPerformed

    private void jButtonCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCompraMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCompraMouseEntered

    private void jButtonCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCompraMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCompraMouseExited

    private void jButtonCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCompraActionPerformed

    private void jButtonVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVendaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVendaMouseEntered

    private void jButtonVendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVendaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVendaMouseExited

    private void jButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVendaActionPerformed

    private void jButtonHistoricoClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHistoricoClienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHistoricoClienteMouseEntered

    private void jButtonHistoricoClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHistoricoClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHistoricoClienteMouseExited

    private void jButtonHistoricoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoricoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHistoricoClienteActionPerformed

    private void jButtonEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEstoqueMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEstoqueMouseEntered

    private void jButtonEstoqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEstoqueMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEstoqueMouseExited

    private void jButtonEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEstoqueActionPerformed

    private void jButtonGerRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGerRelatorioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGerRelatorioMouseEntered

    private void jButtonGerRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGerRelatorioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGerRelatorioMouseExited

    private void jButtonGerRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGerRelatorioActionPerformed

    private void jButtonManualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonManualMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManualMouseEntered

    private void jButtonManualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonManualMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManualMouseExited

    private void jButtonManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManualActionPerformed

    private void jButtonSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairMouseEntered

    private void jButtonSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairMouseExited

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JDialogFuncionario jdFuncionario = new JDialogFuncionario(this, true);
        jdFuncionario.setLocationRelativeTo(null);
        jdFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Sair();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        JDialogCidade jdCidade = new JDialogCidade(this, true);
        jdCidade.setLocationRelativeTo(null);
        jdCidade.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jButtonSolicitacaoServiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSolicitacaoServiceMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSolicitacaoServiceMouseExited

    private void jButtonSolicitacaoServiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSolicitacaoServiceMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSolicitacaoServiceMouseEntered

    private void jButtonSolicitacaoServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitacaoServiceActionPerformed
        // TODO add your handling code here:
         JDialogSolicitacaoServico jdSolicitacaoServico = new JDialogSolicitacaoServico(this, true);
        jdSolicitacaoServico.setLocationRelativeTo(jdSolicitacaoServico);
        jdSolicitacaoServico.setVisible(true);
    }//GEN-LAST:event_jButtonSolicitacaoServiceActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        JDialogRelatorio jDialogRelatorio = new JDialogRelatorio(this, true);
        jDialogRelatorio.setLocationRelativeTo(null);
        jDialogRelatorio.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        JDialogConfigBanco jDialogConfigBanco = new JDialogConfigBanco((null), false);
        jDialogConfigBanco.setLocationRelativeTo(null);
        jDialogConfigBanco.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        JDialogSobre jDialogSobre = new JDialogSobre(null, true);
        jDialogSobre.setLocationRelativeTo(null);
        jDialogSobre.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        JDialogConsCliente jdConsCliente = new JDialogConsCliente(this, true);
        jdConsCliente.setLocationRelativeTo(null);
        jdConsCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jButtonSairMENUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMENUMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairMENUMouseEntered

    private void jButtonSairMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMENUMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairMENUMouseExited

    private void jButtonSairMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairMENUActionPerformed
        // TODO add your handling code here:
        Sair();
    }//GEN-LAST:event_jButtonSairMENUActionPerformed

    private void jButtonManualMENUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonManualMENUMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManualMENUMouseEntered

    private void jButtonManualMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonManualMENUMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManualMENUMouseExited

    private void jButtonManualMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManualMENUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonManualMENUActionPerformed

    private void jButtonSobreMENUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSobreMENUMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSobreMENUMouseEntered

    private void jButtonSobreMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSobreMENUMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSobreMENUMouseExited

    private void jButtonSobreMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreMENUActionPerformed
        // TODO add your handling code here
        JDialogSobre jDialogSobre = new JDialogSobre(null, true);
        jDialogSobre.setLocationRelativeTo(null);
        jDialogSobre.setVisible(true);
    }//GEN-LAST:event_jButtonSobreMENUActionPerformed

    private void jButtonGerRelatorioMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGerRelatorioMENUMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGerRelatorioMENUMouseExited

    private void jButtonGerRelatorioMENUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGerRelatorioMENUMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGerRelatorioMENUMouseEntered

    private void jButtonGerRelatorioMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerRelatorioMENUActionPerformed
        // TODO add your handling code here:
        JDialogRelatorio jDialogRelatorio = new JDialogRelatorio(this, true);
        jDialogRelatorio.setLocationRelativeTo(null);
        jDialogRelatorio.setVisible(true);
    }//GEN-LAST:event_jButtonGerRelatorioMENUActionPerformed

    private void jButtonConsultaClienteMENUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultaClienteMENUMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultaClienteMENUMouseEntered

    private void jButtonConsultaClienteMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultaClienteMENUMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultaClienteMENUMouseExited

    private void jButtonConsultaClienteMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaClienteMENUActionPerformed
        JDialogConsCliente jDialogConsCliente = new JDialogConsCliente(this, true);
        jDialogConsCliente.setLocationRelativeTo(jDialogConsCliente);
        jDialogConsCliente.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultaClienteMENUActionPerformed

    private void jButtonOrdemServicoMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOrdemServicoMENUMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOrdemServicoMENUMouseExited

    private void jButtonOrdemServicoMENUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOrdemServicoMENUMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOrdemServicoMENUMouseEntered

    private void jButtonOrdemServicoMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdemServicoMENUActionPerformed
        // TODO add your handling code here:
        JDialogOrdemServico jdOrdemServico = new JDialogOrdemServico(this, true);
        jdOrdemServico.setLocationRelativeTo(jdOrdemServico);
        jdOrdemServico.setVisible(true);
    }//GEN-LAST:event_jButtonOrdemServicoMENUActionPerformed

    private void Sair() {
        String[] opcoes = {"Sim", "Não"};
        int opcao = JOptionPane.showOptionDialog(null, "Tem certeza que deseja sair?", "Mensagem",
                JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[1]);
        if (JOptionPane.YES_OPTION == opcao) {
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonCompra;
    private javax.swing.JButton jButtonConsultaClienteMENU;
    private javax.swing.JButton jButtonEstoque;
    private javax.swing.JButton jButtonGerRelatorio;
    private javax.swing.JButton jButtonGerRelatorioMENU;
    private javax.swing.JButton jButtonHistoricoCliente;
    private javax.swing.JButton jButtonManual;
    private javax.swing.JButton jButtonManualMENU;
    private javax.swing.JButton jButtonOrdemServicoMENU;
    private javax.swing.JButton jButtonProduto;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSairMENU;
    private javax.swing.JButton jButtonSobreMENU;
    private javax.swing.JButton jButtonSolicitacaoService;
    private javax.swing.JButton jButtonVenda;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuCadastro;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemConsultaCidade;
    private javax.swing.JMenu jMenuOrdemServico;
    private javax.swing.JMenu jMenuSolicitacaoServico;
    private javax.swing.JToolBar jtAtalho;
    // End of variables declaration//GEN-END:variables
}
