/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cwsmanager.model.telas;



import br.edu.utfpr.cwsmanager.model.daos.DaoGenerics;
import br.edu.utfpr.cwsmanager.model.daos.TransactionManager;
import br.edu.utfpr.cwsmanager.model.endereco.Cidade;
import br.edu.utfpr.cwsmanager.model.pessoa.Funcionario;
import br.edu.utfpr.cwsmanager.model.util.UtilDatas;
import br.edu.utfpr.cwsmanager.model.util.Validacao;
import java.awt.Color;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author raphaelLira
 */
public class JDialogFuncionario extends javax.swing.JDialog {

    private UtilDatas converteData = new UtilDatas();
    private Funcionario funcionario;
    private Cidade cidade;
    private Validacao validacao;

    /**
     * Creates new form JDialogCliente
     */
    public JDialogFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        habilitaCampos(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupSexo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelCodCliente = new javax.swing.JLabel();
        jLabelNomeCliente = new javax.swing.JLabel();
        jLabelCpfCliente = new javax.swing.JLabel();
        jLabelSexoCliente = new javax.swing.JLabel();
        jRadioButtonMasculinoFuncionario = new javax.swing.JRadioButton();
        jRadioButtonFemininoFuncionario = new javax.swing.JRadioButton();
        jLabelTelPessoalCliente = new javax.swing.JLabel();
        jLabelEmailCliente = new javax.swing.JLabel();
        jTextFieldIdFuncionario = new javax.swing.JTextField();
        jTextFieldNomeFuncionario = new javax.swing.JTextField();
        jFormattedTextFieldTelefonePessoalFuncionario = new javax.swing.JFormattedTextField();
        jTextFieldEmailFuncionario = new javax.swing.JTextField();
        jButtonPesquisarFuncionario = new javax.swing.JButton();
        jLabelCelCliente = new javax.swing.JLabel();
        jFormattedTextFieldCelularFuncionario = new javax.swing.JFormattedTextField();
        jComboBoxEstadoCivil = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextFieldDataNascFuncionario = new javax.swing.JFormattedTextField();
        jLabelDataNascCliente = new javax.swing.JLabel();
        jFormattedTextFieldCpfFuncionario = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNomeEndereco = new javax.swing.JLabel();
        jTextFieldNomeEnderecoFuncionario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldNumEnderecoFuncionario = new javax.swing.JTextField();
        jLabelComplemento = new javax.swing.JLabel();
        jTextFieldComplementoFuncionario = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jLabelCidadeEnd = new javax.swing.JLabel();
        jLabelCep = new javax.swing.JLabel();
        jTextFieldBairroFuncionario = new javax.swing.JTextField();
        jTextFieldPesquisaCodCidadeFuncionario = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButtonPesquisarCidade = new javax.swing.JButton();
        jButtonIncluirCidade = new javax.swing.JButton();
        jTextFieldNomeCidade = new javax.swing.JTextField();
        jTextFieldUFCidade = new javax.swing.JTextField();
        jTextFieldCep = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldLoginFuncionario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPasswordFieldFuncionario = new javax.swing.JPasswordField();
        jPasswordFieldConfirmaSenhaFuncionario = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jButtonGravarFuncionario = new javax.swing.JButton();
        jButtonCancelarFuncionario = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonIncluirFuncionario = new javax.swing.JButton();
        jButtonAlterarFuncionario = new javax.swing.JButton();
        jButtonExcluirFuncionario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionários");

        jLabelCodCliente.setText("Código:");

        jLabelNomeCliente.setText("Nome:*");

        jLabelCpfCliente.setText("CPF:*");

        jLabelSexoCliente.setText("Sexo:");

        GroupSexo.add(jRadioButtonMasculinoFuncionario);
        jRadioButtonMasculinoFuncionario.setText("Masculino");
        jRadioButtonMasculinoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMasculinoFuncionarioActionPerformed(evt);
            }
        });

        GroupSexo.add(jRadioButtonFemininoFuncionario);
        jRadioButtonFemininoFuncionario.setText("Feminino");

        jLabelTelPessoalCliente.setText("Telefone Pessoal:*");

        jLabelEmailCliente.setText("Email:");

        jTextFieldNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeFuncionarioActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldTelefonePessoalFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefonePessoalFuncionario.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldTelefonePessoalFuncionario.setPreferredSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldTelefonePessoalFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelefonePessoalFuncionarioActionPerformed(evt);
            }
        });

        jButtonPesquisarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisa.png"))); // NOI18N
        jButtonPesquisarFuncionario.setToolTipText("Pesquisar Cliente");
        jButtonPesquisarFuncionario.setMaximumSize(new java.awt.Dimension(42, 28));
        jButtonPesquisarFuncionario.setMinimumSize(new java.awt.Dimension(42, 28));
        jButtonPesquisarFuncionario.setPreferredSize(new java.awt.Dimension(42, 28));
        jButtonPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarFuncionarioActionPerformed(evt);
            }
        });

        jLabelCelCliente.setText("Celular:*");

        try {
            jFormattedTextFieldCelularFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCelularFuncionario.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldCelularFuncionario.setPreferredSize(new java.awt.Dimension(42, 28));

        jComboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado", "Divorciado" }));
        jComboBoxEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoCivilActionPerformed(evt);
            }
        });

        jLabel12.setText("Estado Civil:");

        try {
            jFormattedTextFieldDataNascFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataNascFuncionario.setMinimumSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldDataNascFuncionario.setPreferredSize(new java.awt.Dimension(42, 28));
        jFormattedTextFieldDataNascFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataNascFuncionarioActionPerformed(evt);
            }
        });

        jLabelDataNascCliente.setText("Data de Nascimento:*");

        try {
            jFormattedTextFieldCpfFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpfFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCpfFuncionarioActionPerformed(evt);
            }
        });

        jLabel1.setText("* Campos Obrigatórios");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabelDataNascCliente)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jFormattedTextFieldDataNascFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel12)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(110, 110, 110)
                                        .add(jComboBoxEstadoCivil, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                .add(jLabelEmailCliente)
                                .add(99, 99, 99)
                                .add(jTextFieldEmailFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 399, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabelCodCliente)
                                    .add(jLabelNomeCliente)
                                    .add(jLabelCpfCliente)
                                    .add(jLabelSexoCliente))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jFormattedTextFieldCpfFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 247, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jPanel1Layout.createSequentialGroup()
                                            .add(jRadioButtonMasculinoFuncionario)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(jRadioButtonFemininoFuncionario))
                                        .add(jPanel1Layout.createSequentialGroup()
                                            .add(jTextFieldIdFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                            .add(jButtonPesquisarFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(jTextFieldNomeFuncionario)))))
                        .addContainerGap(100, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabelTelPessoalCliente)
                                .add(28, 28, 28)
                                .add(jFormattedTextFieldTelefonePessoalFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(51, 51, 51)
                                .add(jLabelCelCliente)
                                .add(18, 18, 18)
                                .add(jFormattedTextFieldCelularFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabelCodCliente)
                        .add(jTextFieldIdFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jButtonPesquisarFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNomeCliente)
                    .add(jTextFieldNomeFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelCpfCliente)
                    .add(jFormattedTextFieldCpfFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelSexoCliente)
                    .add(jRadioButtonMasculinoFuncionario)
                    .add(jRadioButtonFemininoFuncionario))
                .add(14, 14, 14)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelDataNascCliente)
                    .add(jFormattedTextFieldDataNascFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12)
                    .add(jComboBoxEstadoCivil, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(56, 56, 56)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelTelPessoalCliente)
                    .add(jFormattedTextFieldTelefonePessoalFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelCelCliente)
                    .add(jFormattedTextFieldCelularFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelEmailCliente)
                    .add(jTextFieldEmailFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 98, Short.MAX_VALUE)
                .add(jLabel1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pessoal", jPanel1);

        jLabelNomeEndereco.setText("Endereço:*");

        jLabel17.setText("N");

        jLabelComplemento.setText("Complemento:");

        jTextFieldComplementoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComplementoFuncionarioActionPerformed(evt);
            }
        });

        jLabelBairro.setText("Bairro:*");

        jLabelCidadeEnd.setText("Cidade:*");

        jLabelCep.setText("CEP:*");

        jTextFieldPesquisaCodCidadeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaCodCidadeFuncionarioActionPerformed(evt);
            }
        });

        jLabel22.setText("UF:");

        jButtonPesquisarCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisa.png"))); // NOI18N
        jButtonPesquisarCidade.setToolTipText("Pesquisar Cliente");
        jButtonPesquisarCidade.setMaximumSize(new java.awt.Dimension(42, 28));
        jButtonPesquisarCidade.setMinimumSize(new java.awt.Dimension(42, 28));
        jButtonPesquisarCidade.setPreferredSize(new java.awt.Dimension(42, 28));
        jButtonPesquisarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCidadeActionPerformed(evt);
            }
        });

        jButtonIncluirCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/incluir.png"))); // NOI18N
        jButtonIncluirCidade.setToolTipText("Pesquisar Cliente");
        jButtonIncluirCidade.setMaximumSize(new java.awt.Dimension(42, 28));
        jButtonIncluirCidade.setMinimumSize(new java.awt.Dimension(42, 28));
        jButtonIncluirCidade.setPreferredSize(new java.awt.Dimension(42, 28));
        jButtonIncluirCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirCidadeActionPerformed(evt);
            }
        });

        try {
            jTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCepActionPerformed(evt);
            }
        });

        jLabel2.setText("* Campos Obrigatórios");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelNomeEndereco)
                            .add(jLabelComplemento)
                            .add(jLabelBairro)
                            .add(jLabelCidadeEnd)
                            .add(jLabelCep))
                        .add(18, 18, 18)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jPanel2Layout.createSequentialGroup()
                                    .add(jTextFieldNomeEnderecoFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 338, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jLabel17)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                    .add(jTextFieldNumEnderecoFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(jPanel2Layout.createSequentialGroup()
                                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jTextFieldBairroFuncionario)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jTextFieldComplementoFuncionario)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                                            .add(jTextFieldPesquisaCodCidadeFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(jButtonPesquisarCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(jButtonIncluirCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(0, 0, Short.MAX_VALUE))
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jTextFieldNomeCidade))
                                    .add(18, 18, 18)
                                    .add(jLabel22)
                                    .add(18, 18, 18)
                                    .add(jTextFieldUFCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jTextFieldCep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 265, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNomeEndereco)
                    .add(jTextFieldNomeEnderecoFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel17)
                    .add(jTextFieldNumEnderecoFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelComplemento)
                    .add(jTextFieldComplementoFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelBairro)
                    .add(jTextFieldBairroFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabelCidadeEnd)
                        .add(jTextFieldPesquisaCodCidadeFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jButtonPesquisarCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonIncluirCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldNomeCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel22)
                    .add(jTextFieldUFCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(23, 23, 23)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelCep)
                    .add(jTextFieldCep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 187, Short.MAX_VALUE)
                .add(jLabel2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Endereço", jPanel2);

        jLabel10.setText("Login:*");

        jLabel11.setText("Senha:*");

        jTextFieldLoginFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginFuncionarioActionPerformed(evt);
            }
        });

        jLabel13.setText("Confirmar Senha:*");

        jPasswordFieldFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldFuncionarioActionPerformed(evt);
            }
        });

        jPasswordFieldConfirmaSenhaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConfirmaSenhaFuncionarioActionPerformed(evt);
            }
        });

        jLabel3.setText("* Campos Obrigatórios");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(45, 45, 45)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel10)
                            .add(jLabel11)
                            .add(jLabel13))
                        .add(27, 27, 27)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jTextFieldLoginFuncionario, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .add(jPasswordFieldFuncionario)
                            .add(jPasswordFieldConfirmaSenhaFuncionario))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(jTextFieldLoginFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jPasswordFieldFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(jPasswordFieldConfirmaSenhaFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 318, Short.MAX_VALUE)
                .add(jLabel3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Login Sistema", jPanel4);

        jButtonGravarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/gravar.png"))); // NOI18N
        jButtonGravarFuncionario.setText("Gravar");
        jButtonGravarFuncionario.setToolTipText("Gravar Funcionario");
        jButtonGravarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarFuncionarioActionPerformed(evt);
            }
        });

        jButtonCancelarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancelar.png"))); // NOI18N
        jButtonCancelarFuncionario.setText("Cancelar Funcionario");
        jButtonCancelarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarFuncionarioActionPerformed(evt);
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/remove.png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.setToolTipText("Sair da Tela");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonIncluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/incluir.png"))); // NOI18N
        jButtonIncluirFuncionario.setText("Incluir");
        jButtonIncluirFuncionario.setToolTipText("Incluir");
        jButtonIncluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirFuncionarioActionPerformed(evt);
            }
        });

        jButtonAlterarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/alterar.png"))); // NOI18N
        jButtonAlterarFuncionario.setText("Alterar");
        jButtonAlterarFuncionario.setToolTipText("Alterar");
        jButtonAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarFuncionarioActionPerformed(evt);
            }
        });

        jButtonExcluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        jButtonExcluirFuncionario.setText("Exluir");
        jButtonExcluirFuncionario.setToolTipText("Excluir");
        jButtonExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirFuncionarioActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 665, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jButtonIncluirFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButtonAlterarFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButtonExcluirFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButtonGravarFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonCancelarFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(59, 59, 59)
                .add(jButtonSair, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 495, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jButtonGravarFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonCancelarFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonSair, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonExcluirFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonAlterarFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonIncluirFuncionario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarFuncionarioActionPerformed
        habilitaCampos(true);
        
        jButtonAlterarFuncionario.setEnabled(false);
        jButtonExcluirFuncionario.setEnabled(true);
        jButtonIncluirFuncionario.setEnabled(false);

        jButtonCancelarFuncionario.setEnabled(true);
        jButtonGravarFuncionario.setEnabled(true);

        jTextFieldIdFuncionario.setEnabled(false);
        jButtonPesquisarFuncionario.setEnabled(false);
        jTextFieldNomeFuncionario.setEnabled(true);
        jFormattedTextFieldCpfFuncionario.setEnabled(true);
        jRadioButtonMasculinoFuncionario.setEnabled(true);
        jRadioButtonFemininoFuncionario.setEnabled(true);
        jFormattedTextFieldDataNascFuncionario.setEnabled(true);
        jFormattedTextFieldTelefonePessoalFuncionario.setEnabled(true);
        jFormattedTextFieldCelularFuncionario.setEnabled(true);
        jTextFieldEmailFuncionario.setEnabled(true);
        jTextFieldLoginFuncionario.setEnabled(true);
        jPasswordFieldConfirmaSenhaFuncionario.setEnabled(true);
        jPasswordFieldFuncionario.setEnabled(true);
        jTextFieldNomeEnderecoFuncionario.setEnabled(true);
        jTextFieldNumEnderecoFuncionario.setEnabled(true);
        jTextFieldComplementoFuncionario.setEnabled(true);
        jTextFieldBairroFuncionario.setEnabled(true);
        jTextFieldPesquisaCodCidadeFuncionario.setEnabled(true);
        jButtonPesquisarCidade.setEnabled(true);
        jButtonIncluirCidade.setEnabled(true);
        jTextFieldNomeCidade.setEnabled(true);
        jTextFieldUFCidade.setEnabled(true);
        jTextFieldCep.setEnabled(true);

    }//GEN-LAST:event_jButtonAlterarFuncionarioActionPerformed

    private void jButtonExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirFuncionarioActionPerformed
        String[] opcoes = {"Sim", "Não"};
        int opcao = JOptionPane.showOptionDialog(null, "Tem certeza que deseja excluir?", "Confirmação",
                JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[1]);

       if (JOptionPane.OK_OPTION == opcao) 
        try {
            TransactionManager.beginTransaction();
                DaoGenerics<Funcionario> daoFuncionario = new DaoGenerics<>(Funcionario.class);
                daoFuncionario.delete(daoFuncionario.retrieve(Integer.parseInt(jTextFieldIdFuncionario.getText())));
                JOptionPane.showMessageDialog(null, "O registro foi excluido com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                TransactionManager.commit();
        } catch (Exception ex) {
             TransactionManager.rollback();
            Logger.getLogger(JDialogFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearCampos();
    }//GEN-LAST:event_jButtonExcluirFuncionarioActionPerformed

    private void jButtonIncluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirFuncionarioActionPerformed
        clearCampos();
        habilitaCampos(false);
    }//GEN-LAST:event_jButtonIncluirFuncionarioActionPerformed

    private void jButtonGravarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarFuncionarioActionPerformed

               // TODO add your handling code here:
            if (!validaCampos()) {
            return;
        }
        try {
            gravar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            Logger.getLogger(JDialogFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Registro gravado com sucesso.", "Gravar", JOptionPane.INFORMATION_MESSAGE);

        habilitaCampos(true);
        jButtonPesquisarFuncionario.setEnabled(true);

    }//GEN-LAST:event_jButtonGravarFuncionarioActionPerformed

    private void jButtonCancelarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarFuncionarioActionPerformed
        habilitaCampos(false);
        clearCampos();
    }//GEN-LAST:event_jButtonCancelarFuncionarioActionPerformed

    private void jButtonIncluirCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirCidadeActionPerformed

        JDialogCidade cadCidade = new JDialogCidade(this, true);
        cadCidade.setVisible(true);
    }//GEN-LAST:event_jButtonIncluirCidadeActionPerformed

    private void jButtonPesquisarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCidadeActionPerformed

        final JDialogConsCidade consultaCidade = new JDialogConsCidade(this, true);
        consultaCidade.setVisible(true);

        consultaCidade.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cidade = consultaCidade.cidade;
                try {
                    TransactionManager.beginTransaction();
                    cidade = new DaoGenerics<Cidade>(Cidade.class).retrieve(cidade.getId());
                    TransactionManager.commit();
                } catch (Exception ex) {
                    Logger.getLogger(JDialogFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                }
                jTextFieldPesquisaCodCidadeFuncionario.setText(Integer.toString(cidade.getId()));
                jTextFieldNomeCidade.setText(cidade.getNome());
                jTextFieldUFCidade.setText(cidade.getEstado());


            }
        });


    }//GEN-LAST:event_jButtonPesquisarCidadeActionPerformed

    private void jButtonPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarFuncionarioActionPerformed


        final JDialogConsFuncionario consulta = new JDialogConsFuncionario(this, true);
        consulta.setVisible(true);

        consulta.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                funcionario = consulta.funcionario;
                try {
                    TransactionManager.beginTransaction();
                    funcionario = new DaoGenerics<Funcionario>(Funcionario.class).retrieve(funcionario.getId());
                    TransactionManager.commit();
                } catch (Exception ex) {
                    Logger.getLogger(JDialogFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                }
               setFuncionario(funcionario);
               
               habilitaCampos(true);
               jButtonPesquisarFuncionario.setEnabled(true);
            }

            
        });




    }//GEN-LAST:event_jButtonPesquisarFuncionarioActionPerformed

    private void jFormattedTextFieldTelefonePessoalFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefonePessoalFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTelefonePessoalFuncionarioActionPerformed

    private void jTextFieldNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFuncionarioActionPerformed

    private void jRadioButtonMasculinoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMasculinoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMasculinoFuncionarioActionPerformed

    private void jComboBoxEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoCivilActionPerformed

    private void jFormattedTextFieldDataNascFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataNascFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataNascFuncionarioActionPerformed

    private void jFormattedTextFieldCpfFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCpfFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCpfFuncionarioActionPerformed

    private void jTextFieldComplementoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComplementoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldComplementoFuncionarioActionPerformed

    private void jTextFieldPesquisaCodCidadeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaCodCidadeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaCodCidadeFuncionarioActionPerformed

    private void jTextFieldCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCepActionPerformed

    private void jPasswordFieldFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldFuncionarioActionPerformed

    private void jTextFieldLoginFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginFuncionarioActionPerformed

    private void jPasswordFieldConfirmaSenhaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmaSenhaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldConfirmaSenhaFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogFuncionario dialog = new JDialogFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupSexo;
    private javax.swing.JButton jButtonAlterarFuncionario;
    private javax.swing.JButton jButtonCancelarFuncionario;
    private javax.swing.JButton jButtonExcluirFuncionario;
    private javax.swing.JButton jButtonGravarFuncionario;
    private javax.swing.JButton jButtonIncluirCidade;
    private javax.swing.JButton jButtonIncluirFuncionario;
    private javax.swing.JButton jButtonPesquisarCidade;
    private javax.swing.JButton jButtonPesquisarFuncionario;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxEstadoCivil;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelularFuncionario;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfFuncionario;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascFuncionario;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefonePessoalFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCelCliente;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidadeEnd;
    private javax.swing.JLabel jLabelCodCliente;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelCpfCliente;
    private javax.swing.JLabel jLabelDataNascCliente;
    private javax.swing.JLabel jLabelEmailCliente;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelNomeEndereco;
    private javax.swing.JLabel jLabelSexoCliente;
    private javax.swing.JLabel jLabelTelPessoalCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordFieldConfirmaSenhaFuncionario;
    private javax.swing.JPasswordField jPasswordFieldFuncionario;
    private javax.swing.JRadioButton jRadioButtonFemininoFuncionario;
    private javax.swing.JRadioButton jRadioButtonMasculinoFuncionario;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldBairroFuncionario;
    private javax.swing.JFormattedTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldComplementoFuncionario;
    private javax.swing.JTextField jTextFieldEmailFuncionario;
    private javax.swing.JTextField jTextFieldIdFuncionario;
    private javax.swing.JTextField jTextFieldLoginFuncionario;
    private javax.swing.JTextField jTextFieldNomeCidade;
    private javax.swing.JTextField jTextFieldNomeEnderecoFuncionario;
    private javax.swing.JTextField jTextFieldNomeFuncionario;
    private javax.swing.JTextField jTextFieldNumEnderecoFuncionario;
    private javax.swing.JTextField jTextFieldPesquisaCodCidadeFuncionario;
    private javax.swing.JTextField jTextFieldUFCidade;
    // End of variables declaration//GEN-END:variables

   public void gravar() throws Exception {
        funcionario = null;

        if (jTextFieldIdFuncionario.getText().isEmpty()) {
            funcionario = new Funcionario();
        } else {
            funcionario = new DaoGenerics<Funcionario>(Funcionario.class).retrieve(Integer.parseInt(jTextFieldIdFuncionario.getText()));
        }
        TransactionManager.beginTransaction();
        funcionario.setNome(jTextFieldNomeFuncionario.getText().trim());
        funcionario.setCpf(jFormattedTextFieldCpfFuncionario.getText().trim());
        funcionario.setSexo((jRadioButtonMasculinoFuncionario.isSelected()) ? "M" : "F");
        funcionario.setEstadoCivil(jComboBoxEstadoCivil.getSelectedItem().toString());
        funcionario.setDataNascimento(converteData.toDate(jFormattedTextFieldDataNascFuncionario.getText().trim()));
        funcionario.setTelPessoal(jFormattedTextFieldTelefonePessoalFuncionario.getText().trim());
        funcionario.setCelular(jFormattedTextFieldCelularFuncionario.getText().trim());
        funcionario.setEmail(jTextFieldEmailFuncionario.getText().trim());
        funcionario.setLogin(jTextFieldLoginFuncionario.getText().trim());
        funcionario.setSenha(jPasswordFieldFuncionario.getText().trim());


        funcionario.getEndereco().setNomeEndereco(jTextFieldNomeEnderecoFuncionario.getText().trim());
        funcionario.getEndereco().setNumero(Integer.parseInt(jTextFieldNumEnderecoFuncionario.getText().trim()));
        funcionario.getEndereco().setComplemento(jTextFieldComplementoFuncionario.getText().trim());
        funcionario.getEndereco().setBairro(jTextFieldBairroFuncionario.getText().trim());
        funcionario.getEndereco().getCidade().setId(Integer.parseInt(jTextFieldPesquisaCodCidadeFuncionario.getText().trim()));
        funcionario.getEndereco().setCep(jTextFieldCep.getText().trim());


        new DaoGenerics<Funcionario>(Funcionario.class).persist(funcionario);
        TransactionManager.commit();
       
    }

    private void setFuncionario(Funcionario funcionario) {
        jTextFieldIdFuncionario.setText(Integer.toString(funcionario.getId()));
        jTextFieldNomeFuncionario.setText(funcionario.getNome());
        jFormattedTextFieldCpfFuncionario.setText(funcionario.getCpf());
        jRadioButtonMasculinoFuncionario.setSelected((funcionario.getSexo().equals("M") ? true : false));
        jComboBoxEstadoCivil.setSelectedItem(funcionario);
        jFormattedTextFieldTelefonePessoalFuncionario.setText(funcionario.getTelPessoal());
        jFormattedTextFieldCelularFuncionario.setText(funcionario.getCelular());
        jFormattedTextFieldDataNascFuncionario.setText(converteData.toString(funcionario.getDataNascimento()));
        jTextFieldEmailFuncionario.setText(funcionario.getEmail());
        jTextFieldLoginFuncionario.setText(funcionario.getLogin());
        jPasswordFieldConfirmaSenhaFuncionario.setText(funcionario.getSenha());
        jPasswordFieldFuncionario.setText(funcionario.getSenha());
       

        jTextFieldNomeEnderecoFuncionario.setText(funcionario.getEndereco().getNomeEndereco());
        jTextFieldNumEnderecoFuncionario.setText(Integer.toString(funcionario.getEndereco().getNumero()));
        jTextFieldComplementoFuncionario.setText(funcionario.getEndereco().getComplemento());
        jTextFieldBairroFuncionario.setText(funcionario.getEndereco().getBairro());
        jTextFieldPesquisaCodCidadeFuncionario.setText(Integer.toString(funcionario.getEndereco().getCidade().getId()));
        jTextFieldNomeCidade.setText(funcionario.getEndereco().getCidade().getNome());
        jTextFieldUFCidade.setText(funcionario.getEndereco().getCidade().getEstado());
        jTextFieldCep.setText(funcionario.getEndereco().getCep());


    }

    private void clearCampos() {
        jTextFieldIdFuncionario.setText("");
        jTextFieldNomeFuncionario.setText("");
        jFormattedTextFieldCpfFuncionario.setText("");
        jRadioButtonMasculinoFuncionario.setSelected(true);
        jFormattedTextFieldTelefonePessoalFuncionario.setText("");
        jFormattedTextFieldCelularFuncionario.setText("");
        jFormattedTextFieldDataNascFuncionario.setText("");
        jTextFieldEmailFuncionario.setText("");
        jTextFieldLoginFuncionario.setText("");
        jPasswordFieldFuncionario.setText("");
        jTextFieldNomeEnderecoFuncionario.setText("");
        jTextFieldNumEnderecoFuncionario.setText("");
        jTextFieldComplementoFuncionario.setText("");
        jTextFieldBairroFuncionario.setText("");
        jTextFieldPesquisaCodCidadeFuncionario.setText("");
        jTextFieldNomeCidade.setText("");
        jTextFieldUFCidade.setText("");
        jTextFieldCep.setText("");



    }

    private void habilitaCampos(boolean comando) {

        jButtonAlterarFuncionario.setEnabled(comando);
        jButtonExcluirFuncionario.setEnabled(comando);
        jButtonIncluirFuncionario.setEnabled(comando);

        jButtonCancelarFuncionario.setEnabled(!comando);
        jButtonGravarFuncionario.setEnabled(!comando);

        jTextFieldIdFuncionario.setEnabled(comando);
        jButtonPesquisarFuncionario.setEnabled(!comando);
        jTextFieldNomeFuncionario.setEnabled(!comando);
        jFormattedTextFieldCpfFuncionario.setEnabled(!comando);
        jRadioButtonMasculinoFuncionario.setEnabled(!comando);
        jRadioButtonFemininoFuncionario.setEnabled(!comando);

        jComboBoxEstadoCivil.setEnabled(!comando);
        
        jFormattedTextFieldTelefonePessoalFuncionario.setEnabled(!comando);
        jFormattedTextFieldCelularFuncionario.setEnabled(!comando);
        jFormattedTextFieldDataNascFuncionario.setEnabled(!comando);
        jTextFieldNomeEnderecoFuncionario.setEnabled(!comando);
        jTextFieldNumEnderecoFuncionario.setEnabled(!comando);
        jTextFieldComplementoFuncionario.setEnabled(!comando);
        jTextFieldBairroFuncionario.setEnabled(!comando);
        jTextFieldPesquisaCodCidadeFuncionario.setEnabled(!comando);
        jButtonPesquisarCidade.setEnabled(!comando);
        jButtonIncluirCidade.setEnabled(!comando);
        jTextFieldNomeCidade.setEnabled(!comando);
        jTextFieldUFCidade.setEnabled(!comando);
        jTextFieldCep.setEnabled(!comando);


        jTextFieldEmailFuncionario.setEnabled(!comando);
        jTextFieldLoginFuncionario.setEnabled(!comando);
        jPasswordFieldConfirmaSenhaFuncionario.setEnabled(!comando);
        jPasswordFieldFuncionario.setEnabled(!comando);
        
        
       



    }

    private boolean validaCampos() {
        if (jTextFieldNomeFuncionario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jTextFieldNomeFuncionario.grabFocus();
            validaComponente(jTextFieldNomeFuncionario, false);
            return false;
        }


         if (jFormattedTextFieldCpfFuncionario.getText().replaceAll("[ .\\-/()]", "").isEmpty()) {
            JOptionPane.showMessageDialog(null, "CPF é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldCpfFuncionario.grabFocus();
            validaComponente(jFormattedTextFieldCpfFuncionario, false);
            return false;
        }
 

        if (jFormattedTextFieldDataNascFuncionario.getText().replaceAll("[ /]", "").isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data de Nascimento é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldDataNascFuncionario.grabFocus();
            validaComponente(jFormattedTextFieldDataNascFuncionario, false);
            return false;
        }
 
         
         if (jFormattedTextFieldTelefonePessoalFuncionario.getText().replaceAll("[ ()-]", "").isEmpty()) {
            JOptionPane.showMessageDialog(null, "Telefone Pessoal é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldTelefonePessoalFuncionario.grabFocus();
            validaComponente(jFormattedTextFieldTelefonePessoalFuncionario, false);
            return false;
        }
 

        if (jFormattedTextFieldCelularFuncionario.getText().replaceAll("[ ()-]", "").isEmpty()) {
            JOptionPane.showMessageDialog(null, "Celular é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldCelularFuncionario.grabFocus();
            validaComponente(jFormattedTextFieldCelularFuncionario, false);
            return false;
        }

        
        if (!jTextFieldEmailFuncionario.getText().isEmpty()) {
            validacao = new Validacao();
            if (!validacao.validarEmail(jTextFieldEmailFuncionario.getText().trim())) {
                JOptionPane.showMessageDialog(null, "Email nao é valido!", "Atençao!", JOptionPane.WARNING_MESSAGE);
                jTextFieldEmailFuncionario.grabFocus();
                validaComponente(jTextFieldNomeFuncionario, false);
                return false;
            }
            if (jTextFieldNomeEnderecoFuncionario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Endereço é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
                jTextFieldNomeEnderecoFuncionario.grabFocus();
                return false;
            }

            if (jTextFieldNumEnderecoFuncionario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Numero é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
                jTextFieldNumEnderecoFuncionario.grabFocus();
                return false;
            }
            if (jTextFieldBairroFuncionario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Bairro é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
                jTextFieldBairroFuncionario.grabFocus();
                return false;
            }

           if (jTextFieldBairroFuncionario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bairro é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
           jTextFieldBairroFuncionario.grabFocus();
           return false;
        }  

            if (jTextFieldCep.getText().replaceAll("[ -]", "").isEmpty()) {
                JOptionPane.showMessageDialog(null, "CEP é Obrigatório!", "Atençao!", JOptionPane.WARNING_MESSAGE);
                jTextFieldCep.grabFocus();
                return false;

            };
        }
        return true;
       
    }
    
    public static boolean validaComponente(Component component, boolean valido) {
        // faz casting para jcomponent
        // somente jComponent possui os metodos setBorder() e grabFocus()
        JComponent jComponent = (JComponent)component;

        // muda cor da borda
        if (!valido) {
            jComponent.setBorder(new LineBorder(Color.RED));
            jComponent.grabFocus();
        } else {
            jComponent.setBorder(new LineBorder(Color.GRAY));
        }
        return valido;
    }
    
//    public static boolean validaEmail(String email) {
//        //return Pattern.matches(".+@.+\\.[a-z]+", email) ;
//        return Pattern.matches("^[\\w-]+(\\.[\\w-]+)*@([\\w-]+\\.)+[a-zA-Z]{2,7}$", email);
//    }
}